### ISSUE TITLE
Confused about export default

### ISSUE THREAD

**Issue by PeterShinners** [DrkSephy/es6-cheatsheet#52]
I'm fairly new to ES6 and the section of ES6 exports left me confused. On reading it's not clear to me what it is actually doing, which makes it difficult to understand why it is a best practice. It also doesn't appear similar to the CommonJS approach, even though it is stated to be similar.

Wonderful guide and overview, thanks!

**Comment by DrkSephy** [comment]
Exporting simply makes functions / values / objects (etc.) available to be imported for use inside of another module. In CommonJS, it is common to simply export an entire object containing references to functions, like so:

``` javascript
function sumTwo(a, b) {
    return a + b;
}

function sumThree(a, b, c) {
    return a + b + c;
}

let api = {
    sumTwo,
    sumThree
};

module.exports = api;
```

By doing that, we simply export one value (`api`) - which I've noticed is a common trend in CommonJS. It makes code more concise and is an easy pattern to follow, allowing each module to have a clear purpose of what it will do and what it will export. 

Similarly, using `export default <value>` in ES6 is a good practice (as opposed to doing named exports, or other methods of exporting) because it allows a consistent baseline - it is clear what each module will do, and what it will export. Moreover, it exports just a single value, which is consistent with the pattern in CommonJS stated above.

These may be opinionated thoughts, but I feel that following them has great benefits and prevents having to think about "how should I build my modules, or what should they export". I think it's simpler to stick to one consistent export pattern above all else. I hope this was helpful!

**Comment by PeterShinners** [comment]
What I'm not clear on is the difference between `export` and `export default`

**Comment by DrkSephy** [comment]
The keyword export simply is used inline to export one thing:

``` javascript
// CommonJS
module.exports = function sumTwo(a, b) {
    return a + b;
}

module.exports = function sumThree(a, b, c) {
    return a + b + c;
}
```

``` javascript
// ES6
export function sumTwo(a, b) {
    return a + b;
}

export function sumThree(a, b, c) {
    return a + b + c;
}
```

As seen in these two examples, we have to call `export` twice to export two different things. In my first response, I'm showing how it's more common to use `export default` to export a single object containing references to functions - again, exporting **a single thing**, as opposed to exporting multiple things using `export`. They are simply different flavors of exporting (similar with importing), and I'm advocating using `export default` to export a single object of function references - as opposed to prepending `export` to each thing I want to export.

**Comment by sahat** [comment]
@PeterShinners From what I understand, when you `export default`, you can `import` module directly, like so:

``` js
import React from 'react';

// ES5:
var React = require('react');
```

When you `export` multiple functions, you can `import` individual functions using braces notation:

``` js
// file1.js
export function foo() {

}

export function bar() {

}
```

``` js
// file2.js
import { foo, bar } from './file1';

//ES5:
var foo = require('./file1').foo;
var bar = require('./file1').bar;
```

**Comment by sahat** [comment]
On a personal note, I usually use multiple `exports` in my **utils.js** file, so that I can pick and choose which functions I want to import from that file. And I use `export default` when exporting React components, because I want to import the entire module.

**Comment by DrkSephy** [comment]
Thanks for weighing in, @sahat! Great tips :+1:

**Comment by tanveer12332** [comment]
import \* as express from "express";
var User = require('../models/register-user');
i m using import for this method and this is working fine
