### ISSUE TITLE
[section] async-await explanation

### ISSUE THREAD

**Issue by lnfnunes** [DrkSephy/es6-cheatsheet#88]
In the _async-await_ section you say _"I highly recommend using them over Generators + Promises"_ but you don't tell **why**. Could you link some article or explain the reason why it's better ?

Tks

**Comment by DrkSephy** [comment]
Hey @lnfnunes, in short `async-await` is recommended because of it's simplicity and verbosity in handling asynchronous actions in a synchronous looking way. Using Generators + Promises becomes very verbose, and using several Promises in a row eventually leads to something similar to callback hell. [Here](https://ponyfoo.com/articles/understanding-javascript-async-await) is a really great article for reading about `async-await` and how it stacks up to predecessors (Promises, Generators + Promises, etc).

**Comment by lnfnunes** [comment]
@DrkSephy Thank you for your reply.
I was wondering it would be nice to be in the readme for everyone, don't you think ?
Should I suggest a PR or do you add it by your own words ?

**Comment by DrkSephy** [comment]
We can leave it as is, at this point in time using `async-await` is widely used.
